name: discord-bot-dev
services:
  postgres:
    image: postgres:17
    container_name: discord-bot-postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discord_bot_dev
    ports:
      - "5432:5432"
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
